// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncmgxsrlzbqyqkowomkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jbWd4c3JsemJxeXFrb3dvbWtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NTYzOTYsImV4cCI6MjA1OTIzMjM5Nn0.41DVlU27hCbBqJxFYqi-iaxZp7OxnwXaMJFYDhOkjIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);